#!/usr/bin/env bash
source /home/pi/miniforge3/etc/profile.d/conda.sh
conda activate flask-env
python3 -m gunicorn --bind 0.0.0.0:8080 --workers=1 --timeout 40 --chdir /home/pi/Documents/CL-Controller 'wsgi:main()'