#!/usr/bin/env bash
source /home/pi/miniforge3/etc/profile.d/conda.sh
conda activate flask-env
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH
python3 -m gunicorn  --bind 0.0.0.0:8080 --preload --workers=1 -k gevent --timeout 40 --chdir "$SCRIPTPATH"  'wsgi:main(video=True)'
